[package]
name = "compression-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
snap = "1.1"
lz4 = "1.24"
zstd = "0.13"
xz2 = "0.1"
lzma-rs = "0.3"
miniz_oxide = "0.7"
lz4_flex = "0.11"
libdeflater = "1.20"
